---
  - name: "Playing with Ansible and Git"
    hosts: "all"
    vars:
      env_key: "viveraventura"
    connection: local 
    tasks:
    - name: Executando Ansible do servidor.
      shell: ansible-playbook --connection=local --inventory 127.0.0.1, --limit 127.0.0.1 /tmp/BackupVolumeToAWS.yml
